/*
  # RefreshRate Core Module - Database Schema v3.2.0

  ## Summary
  Core database schema for the AGI Shell CMS RefreshRate module. Provides system-wide
  refresh rate management, state tracking, revision control, and module registry.

  ## New Tables

  ### 1. user_roles
  - `id` (bigint, auto-increment, primary key)
  - `user_id` (uuid, references auth.users)
  - `role` (text, not null) - Role name (e.g., 'admin', 'system')
  - `created_at` (timestamptz, default now())

  Purpose: Role-based access control for system features

  ### 2. system_revision
  - `key` (text, primary key) - Unique key for revision tracking
  - `revision` (bigint, default 0) - Current revision number
  - `updated_at` (timestamptz, default now()) - Last update timestamp

  Purpose: Global revision counter for change detection and cache invalidation

  ### 3. refresh_policy
  - `id` (bigint, auto-increment, primary key)
  - `default_interval` (int, default 5000) - Default refresh interval in ms
  - `module_interval` (int, default 5000) - Module-specific interval
  - `settings_interval` (int, default 5000) - Settings refresh interval
  - `dashboard_interval` (int, default 10000) - Dashboard refresh interval
  - `updated_at` (timestamptz, default now())

  Purpose: Centralized refresh policy configuration per context

  ### 4. module_registry
  - `id` (text, primary key) - Unique module identifier
  - `version` (text, not null) - Module version (semver)
  - `type` (text, not null) - Module type (core, internal, external)
  - `install_source` (text, not null) - Installation source
  - `enabled` (boolean, default true) - Module enabled status
  - `created_at` (timestamptz, default now())
  - `updated_at` (timestamptz, default now())

  Purpose: Basic module registration and lifecycle tracking

  ## Security (RLS)
  - All tables have RLS enabled
  - service_role has full access to all tables
  - authenticated users with 'admin' or 'system' role can read all tables
  - Regular users have no access (admin/system only)

  ## Important Notes
  1. All operations use IF NOT EXISTS / IF EXISTS for idempotency
  2. Indexes are created for optimal query performance
  3. RLS policies enforce strict role-based access control
  4. service_role bypass RLS for edge functions
  5. All timestamps use timestamptz for timezone awareness
*/

-- ================================================
-- 0) user_roles – Role model for RLS (Admin/System)
-- ================================================
CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id_role
  ON user_roles(user_id, role);

-- ================================================
-- 1) system_revision – Global revision table
-- ================================================
CREATE TABLE IF NOT EXISTS system_revision (
  key TEXT PRIMARY KEY,
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================================================
-- 2) refresh_policy – Central refresh policy
-- ================================================
CREATE TABLE IF NOT EXISTS refresh_policy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  default_interval INT NOT NULL DEFAULT 5000,
  module_interval INT NOT NULL DEFAULT 5000,
  settings_interval INT NOT NULL DEFAULT 5000,
  dashboard_interval INT NOT NULL DEFAULT 10000,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_refresh_policy_updated_at
  ON refresh_policy(updated_at DESC);

-- ================================================
-- 3) module_registry – Simple module registry
-- ================================================
CREATE TABLE IF NOT EXISTS module_registry (
  id TEXT PRIMARY KEY,
  version TEXT NOT NULL,
  type TEXT NOT NULL,
  install_source TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================================================
-- RLS: system_revision
-- ================================================
ALTER TABLE system_revision ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_system_revision"
  ON system_revision
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "admin_read_system_revision"
  ON system_revision
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'system')
    )
  );

-- ================================================
-- RLS: refresh_policy
-- ================================================
ALTER TABLE refresh_policy ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_refresh_policy"
  ON refresh_policy
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "admin_read_refresh_policy"
  ON refresh_policy
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'system')
    )
  );

-- ================================================
-- RLS: module_registry
-- ================================================
ALTER TABLE module_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_module_registry"
  ON module_registry
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "admin_read_module_registry"
  ON module_registry
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'system')
    )
  );

-- ================================================
-- RLS: user_roles (MUST be defined AFTER usage in other policies)
-- ================================================
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_user_roles"
  ON user_roles
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "admin_read_user_roles"
  ON user_roles
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM user_roles ur
      WHERE ur.user_id = auth.uid()
      AND ur.role IN ('admin', 'system')
    )
  );
