-- ================================================
-- 0) user_roles – Rollenmodell für RLS (Admin/System)
-- ================================================
CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id_role
  ON user_roles(user_id, role);

-- ================================================
-- 1) system_revision – globale Revisions-Tabelle
-- ================================================
CREATE TABLE IF NOT EXISTS system_revision (
  key TEXT PRIMARY KEY,
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================================================
-- 2) refresh_policy – zentrale Refresh-Policy
-- ================================================
CREATE TABLE IF NOT EXISTS refresh_policy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  default_interval INT NOT NULL DEFAULT 5000,
  module_interval INT NOT NULL DEFAULT 5000,
  settings_interval INT NOT NULL DEFAULT 5000,
  dashboard_interval INT NOT NULL DEFAULT 10000,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_refresh_policy_updated_at
  ON refresh_policy(updated_at DESC);

-- ================================================
-- 3) module_registry – einfache Modul-Registry
-- ================================================
CREATE TABLE IF NOT EXISTS module_registry (
  id TEXT PRIMARY KEY,
  version TEXT NOT NULL,
  type TEXT NOT NULL,
  install_source TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================================================
-- RLS: system_revision
-- ================================================
ALTER TABLE system_revision ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_system_revision"
  ON system_revision
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "admin_read_system_revision"
  ON system_revision
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'system')
    )
  );

-- ================================================
-- RLS: refresh_policy
-- ================================================
ALTER TABLE refresh_policy ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_refresh_policy"
  ON refresh_policy
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "admin_read_refresh_policy"
  ON refresh_policy
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'system')
    )
  );

-- ================================================
-- RLS: module_registry
-- ================================================
ALTER TABLE module_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all_module_registry"
  ON module_registry
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "admin_read_module_registry"
  ON module_registry
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM user_roles
      WHERE user_id = auth.uid()
      AND role IN ('admin', 'system')
    )
  );
